device:
  # The default username and password of the system. Normally a plaintext password would be a security concern, however the
  # DART is isolated from the Internet and the password is meant to be common knowledge.
  # Also note there appear to be security requirements enabled that disallow this password being simpler. Note sure how to
  # disable.
  user1: root
  user1pass: GoZipsFall2023!!

include:
  file: trixie-minbase.yaml

image:
  # TODO(Barach): Resize this
  boot_part_size: 200%
  root_part_size: 300%
  name: dart_os

layer:
  device: dart-device
  software: dart-software
  splash: rpi-splash-screen
  dhcp: dhcp-server
  ssh: openssh-server

zre_cantools:
  path: ./src/zre_cantools/

ssh:
  pubkey_user1: ./keys/id_rsa.pub

splash:
  image_path: ${@SRCROOT}/splash.tga